/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BLANK = 5;
  /** RegularExpression Id. */
  int LCURLY = 6;
  /** RegularExpression Id. */
  int RCURLY = 7;
  /** RegularExpression Id. */
  int LET = 8;
  /** RegularExpression Id. */
  int ID = 9;
  /** RegularExpression Id. */
  int ERROR = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 4>",
    "\" \"",
    "\"(\"",
    "\")\"",
    "\"let\"",
    "<ID>",
    "<ERROR>",
  };

}
