/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAR = 6;
  /** RegularExpression Id. */
  int RPAR = 7;
  /** RegularExpression Id. */
  int LET = 8;
  /** RegularExpression Id. */
  int LETREC = 9;
  /** RegularExpression Id. */
  int LAMBDA = 10;
  /** RegularExpression Id. */
  int LAMBDAREC = 11;
  /** RegularExpression Id. */
  int INTEGER = 12;
  /** RegularExpression Id. */
  int ID = 13;
  /** RegularExpression Id. */
  int PLUS = 14;
  /** RegularExpression Id. */
  int IF0 = 15;
  /** RegularExpression Id. */
  int IFNULL = 16;
  /** RegularExpression Id. */
  int PRIME = 17;
  /** RegularExpression Id. */
  int ASSIGN = 18;
  /** RegularExpression Id. */
  int ERROR = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"(\"",
    "\")\"",
    "\"let\"",
    "\"letrec\"",
    "\"lambda\"",
    "\"lambdarec\"",
    "<INTEGER>",
    "<ID>",
    "\"+\"",
    "\"zero?\"",
    "\"null?\"",
    "\"\\\'\"",
    "\":=\"",
    "<ERROR>",
  };

}
