/* Generated By:JavaCC: Do not edit this line. FormatDTraceProfileConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FormatDTraceProfileConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COLON = 3;
  /** RegularExpression Id. */
  int CPU = 4;
  /** RegularExpression Id. */
  int ID = 5;
  /** RegularExpression Id. */
  int FUNC = 6;
  /** RegularExpression Id. */
  int NAME = 7;
  /** RegularExpression Id. */
  int BEGIN = 8;
  /** RegularExpression Id. */
  int END = 9;
  /** RegularExpression Id. */
  int TICK = 10;
  /** RegularExpression Id. */
  int DASHES = 11;
  /** RegularExpression Id. */
  int KS = 12;
  /** RegularExpression Id. */
  int INTEGER = 13;
  /** RegularExpression Id. */
  int STACKELEM = 14;
  /** RegularExpression Id. */
  int EOL = 15;
  /** RegularExpression Id. */
  int ERROR = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\":\"",
    "\"CPU\"",
    "\"ID\"",
    "\"FUNCTION\"",
    "\"NAME\"",
    "\"BEGIN\"",
    "\"END\"",
    "<TICK>",
    "<DASHES>",
    "\"Kernel stacks\"",
    "<INTEGER>",
    "<STACKELEM>",
    "<EOL>",
    "<ERROR>",
  };

}
