/* Generated By:JavaCC: Do not edit this line. FormatterConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FormatterConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AMS = 3;
  /** RegularExpression Id. */
  int AMB = 4;
  /** RegularExpression Id. */
  int SLS = 5;
  /** RegularExpression Id. */
  int TLS = 6;
  /** RegularExpression Id. */
  int EVENTS = 7;
  /** RegularExpression Id. */
  int SECONDS = 8;
  /** RegularExpression Id. */
  int EPERS = 9;
  /** RegularExpression Id. */
  int DASHES = 10;
  /** RegularExpression Id. */
  int PRCNT = 11;
  /** RegularExpression Id. */
  int PIPE = 12;
  /** RegularExpression Id. */
  int AT = 13;
  /** RegularExpression Id. */
  int H1 = 14;
  /** RegularExpression Id. */
  int H2 = 15;
  /** RegularExpression Id. */
  int INTEGER = 16;
  /** RegularExpression Id. */
  int FLOAT = 17;
  /** RegularExpression Id. */
  int STACKELEM = 18;
  /** RegularExpression Id. */
  int EOL = 19;
  /** RegularExpression Id. */
  int ERROR = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"Adaptive mutex spin:\"",
    "\"Adaptive mutex block:\"",
    "\"Spin lock spin:\"",
    "\"Thread lock spin:\"",
    "\" events in \"",
    "\" seconds (\"",
    "\" events/sec)\"",
    "<DASHES>",
    "\"%\"",
    "\"|\"",
    "<AT>",
    "<H1>",
    "<H2>",
    "<INTEGER>",
    "<FLOAT>",
    "<STACKELEM>",
    "<EOL>",
    "<ERROR>",
  };

}
